In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../outputs/final_scored_data.csv")

df.head()

,title,description,text,clean_text,emotion_score,urgency_score,length_score,lexical_diversity,readability,0,...,759,760,761,762,763,764,765,766,767,popularity_score
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...,obama lays wreath at arlington national cemete...,0.4939,0,29,0.620690,22.786207,-0.005474,...,0.142581,0.502352,-0.283248,0.179676,-0.411036,-0.025449,-0.001010,0.032178,0.286443,0.537959
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy Ti...,a look at the health of the chinese economy ti...,0.0000,0,31,0.774194,41.647419,-0.231630,...,-0.079060,0.003451,-0.299366,0.140700,-0.227126,-0.147522,-0.081359,0.191058,-0.038014,0.743155
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...,nouriel roubini global economy not back to nou...,0.0000,0,27,0.740741,22.763333,-0.514056,...,-0.136994,0.090418,-0.188665,-0.116814,-0.279714,-0.146320,-0.252204,0.206540,0.121297,0.508826
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ex...,finland gdp expands in q finlands economy expa...,0.1027,0,28,0.857143,6.193571,-0.427680,...,-0.033822,0.209974,-0.055104,0.156997,-0.258347,-0.119826,-0.427578,0.263684,-0.180585,0.353389
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J...",tourism govt spending buoys thai economy in ja...,0.4019,0,35,0.685714,9.361429,-0.275632,...,-0.134615,0.167502,-0.023497,0.141850,-0.260418,-0.147818,-0.346736,0.250537,-0.312874,0.461084

In [3]:
ranked_df = df.sort_values(
    by="popularity_score",
    ascending=False
)

In [4]:
ranked_df["rank"] = range(1, len(ranked_df) + 1)

In [5]:
ranked_df[["title", "popularity_score", "rank"]].head(10)

                                                 title  popularity_score  rank
149  New Microsoft trade-in deal will give you up t...          1.000000     1
414   Microsoft explains why it's still selling Kinect          0.958355     2
270  The Inside Story of Surface Book, Microsoft's ...          0.957779     3
83   Microsoft's HoloLens will ship to developers b...          0.957158     4
163  Lenovo Yoga 900 vs. Microsoft Surface Book: Ne...          0.953400     5
417  Microsoft: Why You Should Be Buying An Xbox On...          0.953302     6
8    Fire claims more than 100-year-old barn in Han...          0.948216     7
196  Google offers Apps for free. Too late, Microso...          0.941344     8
143  Microsoft will pay $200 for your old laptop, o...          0.933551     9
138               UK economy job done? No way: Osborne          0.930507    10

In [6]:
ranked_df.to_csv("../outputs/ranked_news.csv", index=False)

In [7]:
top5 = ranked_df.head(5)

for i, row in top5.iterrows():
    print(f"Rank {row['rank']}:")
    print("Title:", row["title"])
    print("Score:", row["popularity_score"])
    print("-" * 50)

Rank 1:
Title: New Microsoft trade-in deal will give you up to $300 for your old ...
Score: 1.0000000000000002
--------------------------------------------------
Rank 2:
Title: Microsoft explains why it's still selling Kinect
Score: 0.9583554511736514
--------------------------------------------------
Rank 3:
Title: The Inside Story of Surface Book, Microsoft's Next Big Thing
Score: 0.957778725949012
--------------------------------------------------
Rank 4:
Title: Microsoft's HoloLens will ship to developers by March 30
Score: 0.9571579604396048
--------------------------------------------------
Rank 5:
Title: Lenovo Yoga 900 vs. Microsoft Surface Book: New Windows 10 ...
Score: 0.9534000796438236
--------------------------------------------------